// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAk0ipn1Q4SSLZQtThBrEr9-PoWCiDmxI4",
    appId: "1:714518467514:web:c9edb7c2706b7901134383",
    messagingSenderId: "714518467514",
    projectId: "restaurant-platform-67a24",
    authDomain: "restaurant-platform-67a24.firebaseapp.com",
    storageBucket: "restaurant-platform-67a24.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4EKN5_6YSQmdOHS1sa-eRMqw3Qa08Des',
    appId: '1:291183391936:ios:2b5c8a34242a9ad0a16925',
    messagingSenderId: '291183391936',
    projectId: 'restaurant-platform-prod',
    storageBucket: 'restaurant-platform-prod.firebasestorage.app',
    iosBundleId: 'com.example.webDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4EKN5_6YSQmdOHS1sa-eRMqw3Qa08Des',
    appId: '1:291183391936:ios:2b5c8a34242a9ad0a16925',
    messagingSenderId: '291183391936',
    projectId: 'restaurant-platform-prod',
    storageBucket: 'restaurant-platform-prod.firebasestorage.app',
    iosBundleId: 'com.example.webDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATdOiEH-3KOYqB2i8i7MeDUbDlvojwRaE',
    appId: '1:291183391936:web:c72acdd61d121b7ea16925',
    messagingSenderId: '291183391936',
    projectId: 'restaurant-platform-prod',
    authDomain: 'restaurant-platform-prod.firebaseapp.com',
    storageBucket: 'restaurant-platform-prod.firebasestorage.app',
  );

}